project scaffolding
raskovnik/pic-sleuth-backend pull request #1
Opened 2023-06-02 10:42 UTC by raskovnik

2023-06-03 08:29 UTC, st3v3nmw requested changes
Awesome progress so far!!!

2023-06-03 08:29 UTC, st3v3nmw commented on pic_sleuth/config/asgi.py
> +"""
Remove this file, we won't need it. We'll go the `wsgi.py` route

fyi, here's a small intro on asgi https://asgi.readthedocs.io/en/latest/introduction.html

2023-06-03 08:29 UTC, st3v3nmw commented on .gitignore
> +__pycache__
Add `venv/` too

2023-06-03 08:29 UTC, st3v3nmw commented on pic_sleuth/config/settings.py
> +SECRET_KEY = 'django-insecure-td4#33x_sd0-ylizxcng+-g66#%sn21m@vukar(gjh644^7#*!'
Provide the value using an environment variable instead

2023-06-03 08:29 UTC, st3v3nmw commented on pic_sleuth/config/settings.py
> +        "LOCATION": "redis://localhost:6379/1",
Provide the value using an environment variable instead

2023-06-03 08:29 UTC, st3v3nmw commented on pic_sleuth/config/settings.py
> +        'HOST': 'localhost',
Provide the values using environment variables instead

2023-06-03 08:29 UTC, st3v3nmw commented on pic_sleuth/config/settings.py
> +TIME_ZONE = 'UTC'
```suggestion
TIME_ZONE = 'Africa/Nairobi'
```

2023-06-03 08:29 UTC, st3v3nmw commented on pic_sleuth/config/urls.py
> +    path('admin/', admin.site.urls),
Remove the Admin page, it's a good way to learn APIs & Django shell without relying on UIs

2023-06-03 08:29 UTC, st3v3nmw commented on pic_sleuth/config/wsgi.py
> +os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
If our `manage.py` file is at the root directory (outside `pic_sleuth`), change the `DJANGO_SETTINGS_MODULE` to reflect ... `pic_sleuth.config.settings`

2023-06-03 08:29 UTC, st3v3nmw commented on pic_sleuth/manage.py
> +    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
Move outside `pic_sleuth`, same comment as above on `DJANGO_SETTINGS_MODULE`

2023-06-03 08:29 UTC, st3v3nmw commented on pic_sleuth/photos/admin.py
> +from django.contrib import admin
We won't need admin pages, unaeza delete this file

2023-06-03 08:29 UTC, st3v3nmw commented on pic_sleuth/photos/tests.py
> +from django.test import TestCase
Delete this file since all our tests will be in `tests/` and not in our src directory

2023-06-03 08:29 UTC, st3v3nmw commented on pic_sleuth/pytest.ini
> +DJANGO_SETTINGS_MODULE = config.settings
```suggestion
DJANGO_SETTINGS_MODULE = pic_sleuth.config.settings
```

2023-06-03 08:29 UTC, st3v3nmw commented on requirements.txt
> +apturl==0.5.2
Only add the requirements you've added _by hand_. A `pip freeze` dump makes this hard to maintain in future.

We only need: Django, redis libs, coverage, DRF, psycopg, etc

Also, separate the requirements into different files. e.g. base requirements that your app requires at runtime (`requirements/base.txt`), and test requirements only needed when testing (`requirements/test.txt`).

2023-06-03 08:29 UTC, st3v3nmw commented on tests/photos/test_views.py
> +settings.configure()
🙂

I see why you did this. We'll remove this once all our `DJANGO_SETTINGS_MODULE` setting are OK (`pic_sleuth.config.settings`). Make sure you're running your commands from the root directory and `manage.py` is in the root directory as well.

2023-06-03 08:29 UTC, st3v3nmw commented on pic_sleuth/config/settings.py
> +ROOT_URLCONF = 'config.urls'
```suggestion
ROOT_URLCONF = 'pic_sleuth.config.urls'
```

2023-06-03 08:29 UTC, st3v3nmw commented on pic_sleuth/config/settings.py
> +WSGI_APPLICATION = 'config.wsgi.application'
```suggestion
WSGI_APPLICATION = 'pic_sleuth.config.wsgi.application'
```

2023-06-03 20:33 UTC, raskovnik commented on pic_sleuth/config/asgi.py
> +"""
done

2023-06-03 20:33 UTC, raskovnik commented on .gitignore
> +__pycache__
done

2023-06-03 20:35 UTC, raskovnik commented on pic_sleuth/config/settings.py
> +SECRET_KEY = 'django-insecure-td4#33x_sd0-ylizxcng+-g66#%sn21m@vukar(gjh644^7#*!'
done

2023-06-03 20:36 UTC, raskovnik commented on pic_sleuth/config/settings.py
> +        'HOST': 'localhost',
all of them?

2023-06-03 20:36 UTC, raskovnik commented on pic_sleuth/config/settings.py
> +        'HOST': 'localhost',
but for the user seems to return my pc username instead of the value set in the environment file

2023-06-03 20:37 UTC, raskovnik commented on pic_sleuth/config/settings.py
> +TIME_ZONE = 'UTC'
done

2023-06-03 20:38 UTC, raskovnik commented on pic_sleuth/config/urls.py
> +    path('admin/', admin.site.urls),
done

2023-06-03 20:38 UTC, raskovnik commented on pic_sleuth/config/wsgi.py
> +os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
it is inside the pic_sleuth directory

2023-06-03 20:40 UTC, raskovnik commented on pic_sleuth/manage.py
> +    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
when I move it to the root directory it shows errors not known to man

2023-06-03 20:40 UTC, raskovnik commented on pic_sleuth/photos/admin.py
> +from django.contrib import admin
done

2023-06-03 20:40 UTC, raskovnik commented on pic_sleuth/photos/tests.py
> +from django.test import TestCase
done

2023-06-03 20:42 UTC, st3v3nmw commented on pic_sleuth/config/settings.py
> +        'HOST': 'localhost',
> all of them?

name, user, password, & host

2023-06-03 20:42 UTC, st3v3nmw commented on pic_sleuth/config/wsgi.py
> +os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
Should be outside `pic_sleuth`

2023-06-03 20:42 UTC, st3v3nmw commented on pic_sleuth/manage.py
> +    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
Let's see them

2023-06-03 20:43 UTC, raskovnik commented on requirements.txt
> +apturl==0.5.2
I have added the Django, redis libs, coverage, DRF, psycopg,  to the base.txt file

2023-06-03 20:44 UTC, raskovnik commented on tests/photos/test_views.py
> +settings.configure()
when I move manage.py to the root directory the errors are so many...acha I send you the stacktrace

2023-06-04 04:41 UTC, st3v3nmw commented on pic_sleuth/config/settings.py
> +        'HOST': 'localhost',
Unaeza tumia prefix "DB_".. So "DB_USER", "DB_PASSWORD", etc

2023-06-04 12:24 UTC, st3v3nmw requested changes

2023-06-04 12:24 UTC, st3v3nmw commented on manage.py
> +    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
Update this

2023-06-04 12:24 UTC, st3v3nmw commented on requirements.txt
> +apturl==0.5.2
Missing in new files:

pytest==7.3.1
pytest-cov==4.1.0
django-redis==5.2.0

Delete this file after migrating the three

2023-06-04 12:24 UTC, st3v3nmw commented on requirements/base.txt
> +psycopg2
Lock the versions

Plus, you installed psycopg2-binary==2.9.6. Look into using psycopg version 3 instead

2023-06-04 12:33 UTC, st3v3nmw commented on pytest.ini
> +[pytest]
To prevent config "sprawl" (different tools having their own config files), rename this file to `tox.ini`.

To ignore files from coverage reports, add the following:

```ini
[coverage:run]
branch = True
source = pic_sleuth
omit =
  pic_sleuth/config/*
  pic_sleuth/**/migrations/*

[coverage:report]
fail_under = 100
show_missing = True
```

2023-06-04 12:33 UTC, st3v3nmw commented on pytest.ini
> +addopts = --ignore=pic_sleuth/config/*
We've ignored using `coverage:run` instead.

Change to this to avoid specifying the --cov option when running from the terminal. You can now simply run `pytest`.

```suggestion
addopts = --cov=pic_sleuth --durations=25 -n auto -v
```

2023-06-04 12:33 UTC, st3v3nmw commented on pytest.ini
> +norecursedirs = pic_sleuth/*/migrations/*
We've ignored using `coverage:run` instead.

While we're here, you can tell it not to look at the env folders, etc.

```suggestion
norecursedirs = venv build .env bin .cache .tox
```

2023-06-05 15:48 UTC, raskovnik commented on pic_sleuth/config/settings.py
> +        'HOST': 'localhost',
done

2023-06-05 15:50 UTC, raskovnik commented on requirements.txt
> +apturl==0.5.2
done

2023-06-05 15:52 UTC, raskovnik commented on manage.py
> +    os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
done

2023-06-05 15:54 UTC, raskovnik commented on pytest.ini
> +[pytest]
done

2023-06-05 15:58 UTC, raskovnik commented on pytest.ini
> +norecursedirs = pic_sleuth/*/migrations/*
done

2023-06-06 19:29 UTC, st3v3nmw reviewed
Fix the 2 minor issues we merge it

2023-06-06 19:29 UTC, st3v3nmw commented on pic_sleuth/config/settings.py
> +        "LOCATION": "redis://localhost:6379/1",
:eyes:

2023-06-06 19:29 UTC, st3v3nmw commented on requirements/test.txt
> +django-redis==5.2.0
`django-redis` isn't a test library

2023-06-06 20:49 UTC, raskovnik commented on requirements/test.txt
> +django-redis==5.2.0
done

2023-06-07 03:06 UTC, merged